"use client";
import {useEffect,useState} from "react";
import {detectObjects,type DetectedPoint} from "@/lib/detect-objects";
import {ImagePlus,Microscope,Save,Timer,Ruler,ChartNoAxesColumn} from "lucide-react";

export type Measurement={id:string;kind:string;title:string;data:string;imageKey:string|null;createdAt:string};
const fmt=(n:number)=>Number.isFinite(n)?new Intl.NumberFormat("th-TH",{maximumSignificantDigits:4}).format(n):"—";
async function uploadRecord(kind:string,title:string,data:object){
 const form=new FormData();form.set("kind",kind);form.set("title",title);form.set("data",JSON.stringify(data));
 const response=await fetch("/api/measurements",{method:"POST",body:form});if(!response.ok)throw Error("Save failed");
 return await response.json() as Measurement;
}
function chooseFile(f:File|undefined,update:(f:File)=>void,notify:(s:string)=>void){if(!f)return;if(f.size>8_000_000||!["image/jpeg","image/png","image/webp"].includes(f.type)){notify("ภาพต้องเป็น JPG, PNG หรือ WebP ขนาดไม่เกิน 8 MB");return}update(f)}

export function CellCounter({onSaved}:{onSaved:(m:Measurement)=>void}){
 const [file,setFile]=useState<File|null>(null),[url,setUrl]=useState(""),[points,setPoints]=useState<{x:number;y:number;type:"live"|"dead"}[]>([]);
 const [active,setActive]=useState<"live"|"dead">("live"),[mode,setMode]=useState<"hemo"|"general">("hemo"),[squares,setSquares]=useState("4"),[dilution,setDilution]=useState("1");
 const [name,setName]=useState(""),[sample,setSample]=useState(""),[stain,setStain]=useState(""),[magnification,setMagnification]=useState(""),[notes,setNotes]=useState("");
 const [contrast,setContrast]=useState("18"),[minimum,setMinimum]=useState("10"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>()=>{if(url)URL.revokeObjectURL(url)},[url]);
 const live=points.filter(p=>p.type==="live").length,dead=points.length-live;
 const cellsPerMl=Number(squares)>0&&Number(dilution)>0?(live+dead)/Number(squares)*10000*Number(dilution):null;
 function handleFile(f?:File){chooseFile(f,next=>{if(url)URL.revokeObjectURL(url);setFile(next);setUrl(URL.createObjectURL(next));setPoints([])},setMessage)}
 async function auto(){if(!url)return;setBusy(true);try{const found=await detectObjects(url,Number(contrast),Number(minimum),"dark");setPoints(found.map(p=>({...p,type:active})));setMessage(`ระบบเสนอ ${found.length} จุด ตรวจและแก้ไขก่อนบันทึก`)}catch{setMessage("วิเคราะห์ภาพไม่สำเร็จ กรุณาแตะนับเอง")}finally{setBusy(false)}}
 async function save(){if(!file||!name.trim()){setMessage("เพิ่มภาพและชื่อรายการก่อนบันทึก");return}setBusy(true);try{const row=await uploadRecord("cell",name,{sample,mode,live,dead,squares:Number(squares),dilution:Number(dilution),cellsPerMl:mode==="hemo"?cellsPerMl:null,viability:points.length?live/points.length*100:null,points,stain,magnification,notes});onSaved(row);setMessage("บันทึกผลนับเซลล์แล้ว")}catch{setMessage("บันทึกไม่สำเร็จ ลองอีกครั้ง")}finally{setBusy(false)}}
 return <><div className="intro"><div><h1>นับเซลล์</h1><p>ทำเครื่องหมายเซลล์มีชีวิตและเซลล์ตาย ตรวจแก้ผลก่อนบันทึก</p></div></div><section className="panel lab-panel"><div className="segments"><button className={mode==="hemo"?"selected":""} onClick={()=>setMode("hemo")}>Hemocytometer</button><button className={mode==="general"?"selected":""} onClick={()=>setMode("general")}>ภาพทั่วไป</button></div><label className="pick"><ImagePlus size={17}/> เลือกภาพเซลล์<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>handleFile(e.target.files?.[0])}/></label>
 {url?<div className="photo cell-photo"><div className="photo-inner" onClick={e=>{const r=e.currentTarget.getBoundingClientRect();setPoints(p=>[...p,{x:(e.clientX-r.left)/r.width*100,y:(e.clientY-r.top)/r.height*100,type:active}])}}><img src={url} alt="ภาพเซลล์"/>{points.map((p,i)=><button className={"dot "+p.type} key={i} style={{left:p.x+"%",top:p.y+"%"}} onClick={e=>{e.stopPropagation();setPoints(q=>q.filter((_,j)=>j!==i))}} aria-label={"ลบจุด "+(i+1)}>{i+1}</button>)}</div></div>:<div className="placeholder"><Microscope size={34}/><strong>เลือกภาพเพื่อเริ่มนับเซลล์</strong></div>}
 <div className="auto-controls"><label title="ปรับระดับความต่างของจุดกับพื้นหลัง ค่าสูงจะเลือกเฉพาะจุดที่เด่นชัด">ความต่างสี {contrast}<input type="range" min="5" max="55" value={contrast} onChange={e=>setContrast(e.target.value)}/></label><label title="ตัดจุดที่มีพื้นที่เล็กกว่าค่านี้ในภาพที่ระบบย่อเพื่อวิเคราะห์">ขนาดขั้นต่ำ {minimum}<input type="range" min="3" max="80" value={minimum} onChange={e=>setMinimum(e.target.value)}/></label><button onClick={auto} disabled={!url||busy}>นับอัตโนมัติ</button></div>
 <p className="hint">ความต่างสีสูงขึ้นจะนับเฉพาะจุดที่เด่นชัด ขนาดขั้นต่ำสูงขึ้นจะตัดจุดเล็กออก ปรับแล้วตรวจและแก้จุดนับบนภาพ</p><div className="cell-types"><button className={active==="live"?"chosen":""} onClick={()=>setActive("live")}>● มีชีวิต {live}</button><button className={active==="dead"?"chosen":""} onClick={()=>setActive("dead")}>● ตาย {dead}</button><button onClick={()=>setPoints(p=>p.slice(0,-1))} disabled={!points.length}>ย้อนกลับ</button><button onClick={()=>setPoints([])} disabled={!points.length}>ล้างจุด</button></div>
 <div className="lab-results"><div><span>จำนวนเซลล์ทั้งหมด</span><strong>{points.length}</strong></div><div><span>Viability</span><strong>{points.length?fmt(live/points.length*100):"—"}%</strong></div>{mode==="hemo"&&<div><span>ความเข้มข้น</span><strong>{cellsPerMl===null?"—":fmt(cellsPerMl)} <small>cells/mL</small></strong></div>}</div>
 {mode==="hemo"&&<div className="grid"><label>จำนวนช่องใหญ่ที่นับ<input type="number" min="1" value={squares} onChange={e=>setSquares(e.target.value)}/></label><label>Dilution factor<input type="number" min="1" value={dilution} onChange={e=>setDilution(e.target.value)}/></label><p className="wide hint">สูตรสำหรับช่องใหญ่ลึก 0.1 mm: cells/mL = จำนวนที่นับ ÷ จำนวนช่อง × 10⁴ × dilution factor</p></div>}
 <div className="grid"><label>ชื่อรายการ *<input value={name} onChange={e=>setName(e.target.value)} placeholder="เช่น ยีสต์ตัวอย่าง A"/></label></div><details className="extra-details"><summary>เพิ่มรายละเอียดการทดลอง (ไม่บังคับ)</summary><div className="grid"><label>รหัสตัวอย่าง<input value={sample} onChange={e=>setSample(e.target.value)}/></label><label>สีที่ใช้ย้อม<input value={stain} onChange={e=>setStain(e.target.value)} placeholder="Trypan blue"/></label><label>กำลังขยาย<input value={magnification} onChange={e=>setMagnification(e.target.value)} placeholder="400×"/></label><label className="wide">หมายเหตุ<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label></div></details><div className="save"><span>ผลอัตโนมัติใช้การแยกความต่างสี โปรดตรวจแก้ด้วยตา</span><button onClick={save} disabled={busy}><Save size={17}/>บันทึกผล</button></div>{message&&<p role="status" className="lab-message">{message}</p>}</section></>;
}

export function OrganismTool({onSaved}:{onSaved:(m:Measurement)=>void}){
 const [files,setFiles]=useState<File[]>([]),[urls,setUrls]=useState<string[]>([]),[group,setGroup]=useState("plant"),[details,setDetails]=useState("");
 const [results,setResults]=useState<{name:string;scientificName:string;percent:number|null;reason:string}[]>([]),[note,setNote]=useState(""),[provider,setProvider]=useState(""),[selected,setSelected]=useState(""),[name,setName]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>()=>{urls.forEach(u=>URL.revokeObjectURL(u))},[urls]);
 function addImages(list?:FileList|null){if(!list)return;const next=Array.from(list);if(files.length+next.length>5||next.some(f=>f.size>8_000_000||!["image/jpeg","image/png","image/webp"].includes(f.type))||[...files,...next].reduce((n,f)=>n+f.size,0)>20_000_000){setMessage("เลือกภาพ JPG, PNG หรือ WebP สูงสุด 5 ภาพ ภาพละ 8 MB และรวมไม่เกิน 20 MB");return}setFiles(old=>[...old,...next]);setUrls(old=>[...old,...next.map(f=>URL.createObjectURL(f))]);setResults([]);setSelected("");setNote("");setMessage("")}
 function removeImage(i:number){URL.revokeObjectURL(urls[i]);setFiles(old=>old.filter((_,j)=>j!==i));setUrls(old=>old.filter((_,j)=>j!==i));setResults([]);setSelected("")}
 async function analyze(){if(!files.length)return;setBusy(true);setMessage("");setResults([]);try{const form=new FormData();files.forEach(f=>form.append("images",f));form.set("group",group);form.set("details",details);const response=await fetch("/api/identify",{method:"POST",body:form});const data=await response.json() as {error?:string;candidates?:{name:string;scientificName:string;percent:number|null;reason:string}[];note?:string;provider?:string;uncertain?:boolean};if(!response.ok)throw Error(data.error||"วิเคราะห์ภาพไม่สำเร็จ");setResults(data.candidates||[]);setNote(data.note||"");setProvider(data.provider||"");setSelected(data.uncertain?"":data.candidates?.[0]?.scientificName||data.candidates?.[0]?.name||"");if(!data.candidates?.length)setMessage("ภาพยังไม่เพียงพอสำหรับระบุชนิด ลองถ่ายให้ชัดขึ้นหรือเพิ่มรายละเอียด")}catch(e){setMessage(e instanceof Error?e.message:"วิเคราะห์ภาพไม่สำเร็จ")}finally{setBusy(false)}}
 async function save(){if(!files.length||!selected||!name.trim())return;setBusy(true);try{onSaved(await uploadRecord("organism",name,{species:selected,details,candidates:results,note,provider,imagesAnalyzed:files.length,method:"ผู้ใช้ตรวจและยืนยันผล"}));setMessage("บันทึกผลแล้ว")}catch{setMessage("บันทึกไม่สำเร็จ")}finally{setBusy(false)}}
 return <><div className="intro"><div><h1>ระบุสิ่งมีชีวิต</h1><p>ถ่ายภาพหลายมุมของตัวเดียวกันเพื่อช่วยตรวจสอบชนิด</p></div></div><div className="lab-split"><section className="panel lab-panel"><div className="image-actions"><label className="pick"><ImagePlus size={17}/> เพิ่มภาพ<input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{addImages(e.target.files);e.target.value=""}}/></label><label className="pick"><Microscope size={17}/> ถ่ายภาพ<input type="file" accept="image/*" capture="environment" onChange={e=>{addImages(e.target.files);e.target.value=""}}/></label></div>{urls.length?<div className="organism-images">{urls.map((u,i)=><div key={u}><img src={u} alt={"ภาพประกอบ "+(i+1)}/><button onClick={()=>removeImage(i)} aria-label={"ลบภาพ "+(i+1)}>ลบภาพ</button></div>)}</div>:<div className="organism-empty"><ImagePlus size={34}/><span>เพิ่มภาพสิ่งมีชีวิตเพื่อเริ่มวิเคราะห์</span></div>}<p className="hint">เพิ่มได้สูงสุด 5 ภาพ ภาพทั้งหมดต้องเป็นสิ่งมีชีวิตตัวเดียวกันหรือพืชต้นเดียวกัน</p><label className="observation-label">กลุ่มสิ่งมีชีวิต<select value={group} onChange={e=>{setGroup(e.target.value);setResults([]);setSelected("")}}><option value="plant">พืช (บริการระบุพืชเฉพาะทาง)</option><option value="animal">สัตว์</option><option value="microscopic">สิ่งมีชีวิตใต้กล้องจุลทรรศน์</option><option value="unknown">ไม่แน่ใจ</option></select></label><label className="observation-label">รายละเอียดเพิ่มเติม (ไม่บังคับ)<textarea value={details} onChange={e=>setDetails(e.target.value)} placeholder="เช่น พบที่จังหวัดอะไร วันที่พบ ลักษณะดอกหรือใบ กำลังขยาย วิธีการย้อมสี" maxLength={1200}/></label><button className="action identify-action" onClick={analyze} disabled={!files.length||busy}>{busy?"กำลังวิเคราะห์ภาพ…":"วิเคราะห์ภาพ"}</button><p className="hint">คะแนนของ Pl@ntNet เป็นคะแนนจากโมเดล ไม่ใช่ความแม่นยำที่รับประกัน ภาพจุลินทรีย์อาจต้องตรวจเพิ่มเติม</p></section><section className="panel lab-panel"><h2>ผลการระบุชนิด</h2>{results.length?<><p className="hint">{provider} · เลือกผลที่ตรวจสอบแล้วเพื่อบันทึก</p><div className="species-list">{results.map((item,i)=><button key={i} className={selected===(item.scientificName||item.name)?"chosen":""} onClick={()=>setSelected(item.scientificName||item.name)}><strong>{item.name} {item.percent!==null&&<span>{item.percent}%</span>}</strong><small>{item.scientificName}</small><span>{item.reason}</span></button>)}</div>{note&&<p className="hint">{note}</p>}<label className="observation-label">ชื่อรายการ *<input value={name} onChange={e=>setName(e.target.value)} placeholder="เช่น ตัวอย่างจากสวน"/></label><button className="action identify-action" onClick={save} disabled={busy||!selected||!name.trim()}><Save size={17}/> บันทึกผล</button></>:<div className="organism-wait">ผลที่วิเคราะห์จะแสดงที่นี่</div>}{message&&<p role="status" className="lab-message">{message}</p>}</section></div></>;
}

export function MoreTools(){
 const [from,setFrom]=useState("mL"),[to,setTo]=useState("L"),[amount,setAmount]=useState("1000"),[values,setValues]=useState(""),[seconds,setSeconds]=useState(0),[running,setRunning]=useState(false),[hydrogen,setHydrogen]=useState("0.000001");
 useEffect(()=>{if(!running)return;const id=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(id)},[running]);
 const units:Record<string,number>={L:1000,mL:1,µL:.001,g:1000,mg:1,µg:.001};
 const volumeGroup=["L","mL","µL"],massGroup=["g","mg","µg"];
 const converted=(volumeGroup.includes(from)&&volumeGroup.includes(to))||(massGroup.includes(from)&&massGroup.includes(to))?Number(amount)*units[from]/units[to]:null;
 const nums=values.split(/[\s,;]+/).map(Number).filter(Number.isFinite),mean=nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:null;
 const sd=mean!==null&&nums.length>1?Math.sqrt(nums.reduce((a,b)=>a+(b-mean)**2,0)/(nums.length-1)):null;
 return <><div className="intro"><div><h1>เครื่องมือเพิ่มเติม</h1><p>แปลงหน่วย คำนวณ pH สถิติพื้นฐาน และจับเวลา</p></div></div><div className="guide-grid extras"><section className="panel lab-panel"><Ruler/><h2>แปลงหน่วย</h2><div className="grid"><label>ค่า<input type="number" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>จาก<select value={from} onChange={e=>setFrom(e.target.value)}>{Object.keys(units).map(u=><option key={u}>{u}</option>)}</select></label><label>เป็น<select value={to} onChange={e=>setTo(e.target.value)}>{Object.keys(units).map(u=><option key={u}>{u}</option>)}</select></label></div><div className="lab-results"><div><strong>{converted===null?"หน่วยต่างชนิด":fmt(converted)} {converted===null?"":to}</strong></div></div></section><section className="panel lab-panel"><h2>คำนวณ pH</h2><label>ความเข้มข้น H⁺ (mol/L)<input type="number" min="0" step="any" value={hydrogen} onChange={e=>setHydrogen(e.target.value)}/></label><div className="lab-results"><div><span>pH = −log₁₀[H⁺]</span><strong>{Number(hydrogen)>0?fmt(-Math.log10(Number(hydrogen))):"—"}</strong></div></div><p className="hint">ใช้ค่าความเข้มข้นเป็นประมาณค่ากิจกรรมของ H⁺</p></section><section className="panel lab-panel"><ChartNoAxesColumn/><h2>สถิติพื้นฐาน</h2><label>ข้อมูลตัวเลข (คั่นด้วยช่องว่างหรือจุลภาค)<textarea value={values} onChange={e=>setValues(e.target.value)} placeholder="12, 14, 15, 13"/></label><div className="lab-results"><div><span>n</span><strong>{nums.length}</strong></div><div><span>Mean</span><strong>{mean===null?"—":fmt(mean)}</strong></div><div><span>Sample SD</span><strong>{sd===null?"—":fmt(sd)}</strong></div></div></section><section className="panel lab-panel"><Timer/><h2>จับเวลาแล็บ</h2><div className="timer">{String(Math.floor(seconds/3600)).padStart(2,"0")}:{String(Math.floor(seconds%3600/60)).padStart(2,"0")}:{String(seconds%60).padStart(2,"0")}</div><button className="action" onClick={()=>setRunning(!running)}>{running?"หยุด":"เริ่ม"}</button><button className="action secondary" onClick={()=>{setRunning(false);setSeconds(0)}}>รีเซ็ต</button></section></div></>;
}
